themeVolume: theme # no trailing slash
sidenav: false
enabledPrezs:
  - VocPrez
sparqlEndpoint: #{SPARQL_ENDPOINT}#
sparqlUsername: #{SPARQL_USERNAME}#
sparqlPassword: #{SPARQL_PASSWORD}#
port: 8000
demo: true
debug: true
searchEndpoints:
  - name: GA VocPrez
    url: http://ga.surroundaustralia.com/sparql/
  - name: GSQ VocPrez
    url: http://gsq.surroundaustralia.com/sparql/
systemUri: http://gswa.surroundaustralia.com
dataUri: http://example.com
systemInfo:
  Prez:
    title: GSWA Vocabulary Registry
    desc: These vocabs are published by...
  VocPrez:
    title: GSWA Vocabulary Registry
    desc: These vocabs are published by...
  CatPrez:
    title: null
    desc: null
  TimePrez:
    title: null
    desc: null
  SpacePrez:
    title: null
    desc: null
appName: gswa
deploymentMethod: kubernetes # docker, kubernetes or ecs
storageClass: ebs-sc # for kubernetes deployment
version: 0.1.2